version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ../:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - postgres

  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ../:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/app
    depends_on:
      - php-fpm

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
        - POSTGRES_USER=${DB_USER:-postgres}
        - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
        - POSTGRES_DB=${DB_NAME:-postgres}
        - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
        - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
        - "${DB_PORT}:5432"

  telegram-bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    restart: unless-stopped
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres_data:
